In [1]:
import numpy as np

In [2]:
a=5

In [3]:
b=[1,2,3]

In [4]:
c=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
vector = np.array(b)

In [6]:
vector

array([1, 2, 3])

In [7]:
matrix=np.array(c)

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x=np.arange(0,10)

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.78156898, 0.43108699, 0.97713406, 0.96623553, 0.08518624])

In [16]:
np.random.rand(3,3)

array([[0.35437616, 0.11402945, 0.51633904],
       [0.01130724, 0.14565436, 0.80900553],
       [0.99551797, 0.34315742, 0.50629598]])

In [17]:
np.random.randint(10,100)

36

In [18]:
np.random.randint(10,100,20)

array([94, 16, 50, 34, 95, 17, 52, 89, 53, 98, 14, 82, 13, 19, 98, 83, 43,
       17, 92, 50])

In [19]:
rndom_arr= np.random.randint(0,50,10)

In [20]:
rndom_arr

array([12, 36, 19, 28, 19, 40, 39, 39, 37,  8])

In [21]:
rndom_arr.reshape(2,5)

array([[12, 36, 19, 28, 19],
       [40, 39, 39, 37,  8]])

In [22]:
rndom_arr.max()

40

In [23]:
rndom_arr.min()

8

In [24]:
rndom_arr.argmax()

5

In [25]:
rndom_arr.argmin()

9

In [27]:
rndom_arr.shape

(10,)

# Indexing & Slicing Of array

In [30]:
arr = np.arange(20,31)

In [31]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr[3]

23

In [33]:
arr[1:5]

array([21, 22, 23, 24])

In [34]:
arr[:6]

array([20, 21, 22, 23, 24, 25])

In [35]:
arr[4:]

array([24, 25, 26, 27, 28, 29, 30])

In [36]:
arr[0::2]

array([20, 22, 24, 26, 28, 30])

In [37]:
arr[0:3]=100

In [38]:
arr

array([100, 100, 100,  23,  24,  25,  26,  27,  28,  29,  30])

broadcasting

In [39]:
second_arr=np.copy(arr)

In [40]:
second_arr

array([100, 100, 100,  23,  24,  25,  26,  27,  28,  29,  30])

Copy Array

# 2D Array

In [42]:
array2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
array2d[0][1]

2

In [45]:
array2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr = np.arange(1,11)

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
cond_arr= arr>5

In [50]:
cond_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr[cond_arr]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr<3]

array([1, 2])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[:3,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Numpy Operations

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
add = arr+arr

In [60]:
add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
sub = arr-arr

In [62]:
sub

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
scalar = arr + 100

In [64]:
scalar

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [65]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [66]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [67]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [70]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])